# Generated by Django 4.2.6 on 2023-10-10 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 18, 42, 53, 70221)),
        ),
    ]
