# Generated by Django 4.2.6 on 2023-10-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_alter_measurement_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='name',
            new_name='sensor_id',
        ),
    ]
